#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile.ssl for crypto/cversion.c */
  #define CFLAGS "gcc -DOPENSSL_NO_KRB5 -DB_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "linux-mips"
  #define DATE "Tue Jan 26 12:35:31 BNT 2016"
#endif
